name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v3.5.3
        
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
        
      - name: Docker build 
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./conversao-temperatura-2-main/src
          file: ./conversao-temperatura-2-main/src/Dockerfile
          push: true
          tags: |
            romanostd/dev-ops-first-steps:v${{ github.run_number }}
             romanostd/dev-ops-first-steps:v1